### PR TITLE
Nodes to set zappi charge mode, boost and minimum green level

### PR DESCRIPTION
**Pull request by biddster**

### CODE REVIEW

**Comment by Mikee1234K** [comment]
I am not sure how to chase @brookesdjb, I dont really know how github works. But I would love to be able to set charge mode, mgl and boost from Node Red. Most of the other data I wanted I found, but I cannot set anything out of Node Red. If you can tell me how to chase @brookesdjb I would...

**Comment by brookesdjb** [comment]
Il review it this week and take a look at merging :)

**Comment by Mikee1234K** [comment]
Great, thank you. Do these changes include being able to set charging, mgl etc out of Node Red ?

**Comment by brookesdjb** [comment]
No idea, but that was my end goal for the project anyway. Il read through what's included in this pr and roadmap anything that's missing.

**Review by brookesdjb — APPROVED** [review]

**Comment by Mikee1234K** [comment]
Sorry for a probably stupid question... will the pallette show an update then with the new nodes ? ? Its not so far. I have not really got any experience how github works

**Comment by brookesdjb** [comment]
I just published the changes to NPM, so you should be able to update the package (I think you can do that though node-red) and then it will appear

**Pull request merged**
